# Generated by Django 4.2.15 on 2024-09-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bg_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
