# Generated by Django 4.2.16 on 2024-09-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_remove_profile_bg_color_remove_profile_bg_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Science Fiction', 'Science Fiction'), ('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Classic', 'Classic')], max_length=20),
        ),
    ]
