# Generated by Django 4.2.16 on 2024-09-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=555, null=True, upload_to='covers/'),
        ),
    ]
